# Generated by Django 4.2.5 on 2023-10-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='game',
            new_name='article',
        ),
    ]
