# Generated by Django 4.2.5 on 2024-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='game_files'),
        ),
    ]
