version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  flower:
    image: mher/flower:0.9.5
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - 5555:5555

  worker:
    build: .
    command: celery -A djangogame worker -l info
    volumes:
      - .:/code
    depends_on:
      - web

  beat:
    build: .
    command: celery -A djangogame beat -l info
    volumes:
      - .:/code
    depends_on:
      - web

volumes:
  redis_data:
  postgres_data:








