# Generated by Django 4.2.5 on 2023-11-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotuserprofile',
            name='tuser_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
