# Generated by Django 4.2.5 on 2023-12-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0007_alter_tbotuserprofile_tuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateField(auto_now=True)),
                ('question', models.TextField()),
            ],
        ),
    ]
