# Generated by Django 4.2.5 on 2023-11-29 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tbot', '0002_tbotuserprofile_tuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotuserprofile',
            name='tuser_link_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
