# Generated by Django 4.2.5 on 2023-11-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_info'),
        ('tbot', '0003_tbotuserprofile_tuser_link_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbotuserprofile',
            name='tspam',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tbotuserprofile',
            name='tuser_first_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbotuserprofile',
            name='tuser_preference_genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='games.genre'),
            preserve_default=False,
        ),
    ]
