# Generated by Django 4.2.5 on 2023-11-29 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_info'),
        ('tbot', '0004_tbotuserprofile_tspam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotuserprofile',
            name='tuser_preference_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.genre'),
        ),
    ]
