# Generated by Django 4.2.5 on 2023-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0006_alter_tbotuserprofile_tuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbotuserprofile',
            name='tuser_id',
            field=models.IntegerField(unique=True),
        ),
    ]
