# Generated by Django 4.2.5 on 2024-01-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0009_tspam'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
