# Generated by Django 4.2.5 on 2024-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_game_alter_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
