# Generated by Django 4.2.5 on 2024-04-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernumber',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
