# Generated by Django 4.2.5 on 2023-10-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_platform_platform_platform_like_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_favorite', to='games.game'),
        ),
    ]
