# Generated by Django 4.2.5 on 2023-11-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_favourite_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
